/* 
 * File:   Savitch_9thEd_Chap2_PracProb2_Sales Prediction
 * Folder: HW Assignment 1
 * Author: Rafid Sarowar
 * Created on 7/7/2025 
 * Purpose:  Savitch_9thEd_Chap2_PracProb2_Sales Prediction
 */

#include <iostream>  //Input/Output Library
using namespace std;

int main(int argc, char** argv) {
    float TotalGen, EastCoastGen;          // Gnarate of the comapny and east coast percentage genarate variables

    cout << "Program to calculate the Sales Prediction." << endl;                   // Input command
    cout << "Input the total income of the company." << endl;

    cin >> TotalGen;

    EastCoastGen = (TotalGen * 0.58);                                 // The math that calculates the 58% of the total income generated by the company

    cout << "Income generated by the East Coast = " << EastCoastGen;

    return 0;
}